### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by MrWeez** [Steaf23/BingoReloaded#30]
```
[16:04:51 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'BingoReloaded-2_0_0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.2
        at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:380) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:518) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[16:11:54 INFO]: Checking version, please wait...
[16:11:55 INFO]: Current: git-Purpur-2004 (MC: 1.20.1)*
* You are 14 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

**Comment by Steaf23** [comment]
Thanks for your issue, I am aware of this issue and I will fix it shortly. In the meantime, I recommend downloading the file from https://www.spigotmc.org/resources/bingo-reloaded.100278/ as I am pretty sure that version works correctly.

**Comment by Steaf23** [comment]
I have reuploaded the release jar file, it should be fixed now
